Add some icons to mat stepper
e-picsa/picsa-apps pull request #118
Opened 2023-03-27 11:26 UTC by khalifan-kfan

## Description

Add a few icons to thee map stepper in the option tool

## Discussion

This is to handle an issue https://github.com/e-picsa/picsa-apps/pull/103

## Preview

https://picsa.app

## Screenshots / Videos

![image](https://user-images.githubusercontent.com/69305400/227926295-b24ec61e-9c11-47c5-92ac-5db7320a8dbd.png)
![image](https://user-images.githubusercontent.com/69305400/227926487-6575b21a-78c3-44fb-b4dd-4c2fe3c1443b.png)
![image](https://user-images.githubusercontent.com/69305400/227927056-0cd684c6-c5bb-4a62-b172-55e1c55595a9.png)
![image](https://user-images.githubusercontent.com/69305400/227928401-df64a767-952d-447b-b358-02d058001bc5.png)
![image](https://user-images.githubusercontent.com/69305400/227927787-64df7f7a-9a2d-4f69-869a-45ae9fd59d41.png)
![image](https://user-images.githubusercontent.com/69305400/227928134-e7bb2052-f121-4e59-b0cc-758474ba0469.png)

2023-03-27 19:31 UTC, chrismclarke requested changes
Thanks for adding @khalifan-kfan - I like how you've used a bunch of the existing mat-icons where possible and nice idea to try and add custom img tags to include our own svgs.

As mentioned on slack it would be good to refactor the img tags to be custom mat-icons instead, as that way we can more easily apply consistent styling and alignment. But otherwise I think we have a really nice base to demo and handover to research and design teams for final specifications

2023-03-27 22:55 UTC, khalifan-kfan commented
Oh thank you @chrismclarke, I will definitely  modify that. And ping you when I push the changes

2023-04-12 18:37 UTC, chrismclarke approved these changes
Looks good to me, I've included a couple minor non-blocking comments so these can just be resolved during future work. Nice job!

2023-04-12 18:37 UTC, chrismclarke commented on apps/picsa-tools/option-tool/src/app/app.component.ts
> +      const iconName = `picsa_options_${key}`;
nice idea to add a custom prefix to the icons, will make them easier to identify in the source code

2023-04-12 18:37 UTC, chrismclarke commented on apps/picsa-tools/option-tool/src/app/components/editor/editor.component.html
> +                *ngIf="femaleIcon" [src]="femaleIcon" /> -->
nit(non-blocking)
If the code is no longer needed probably cleaner to just remove, git keeps code history if you ever need to recover. There's a few comments in this file that could probably be deleted

2023-04-12 18:37 UTC, merged