Feat: Resource share functionality
e-picsa/picsa-apps pull request #280
Opened 2024-05-27 04:54 UTC by khalifan-kfan

## Description

This feature enables a user to share a resource to others on web and on native devices.

## Discussion

Following issue #58

## Preview

## Screenshots / Videos

<img width="1409" alt="Screenshot 2024-05-27 at 07 53 41" src="https://github.com/e-picsa/picsa-apps/assets/69305400/de1c20c5-b143-435b-8d1c-1dd2dc80b9ce">

2024-06-03 09:04 UTC, chrismclarke requested changes
Looks like definitely headed in the right direction, see a few minor (non-blocking) comments inline and then the one blocking about sharing as an actual file and not just links.

2024-06-09 16:00 UTC, khalifan-kfan commented
Thanks for the feedback @chrismclarke, Let me look into fixing the outlined issues.

2024-06-15 08:52 UTC, khalifan-kfan commented on apps/picsa-tools/resources-tool/src/app/services/resources-tool.service.ts
> +        //api is not compatible with some browser versions
Apparently my chrome browser couldn't either but my safari could

2024-06-15 13:28 UTC, khalifan-kfan commented on apps/picsa-tools/resources-tool/src/app/services/resources-tool.service.ts
> +        });
I may need some help on this part @chrismclarke

2024-06-19 11:40 UTC, chrismclarke approved these changes
Thanks @khalifan-kfan - the issue with sharing as native file was indeed a tricky one. I noticed in the [Share Documentation](https://capacitorjs.com/docs/apis/share#android) that  by default only files stored in the `Cache` directory can be shared (without providing additional permissions), so I needed to add an extra method that allows copying to cache folder (see 6c6d579).

I also noticed play store links weren't sharing correctly (they only are stored as the app id so need extra part of the URL at the start to share), which was fixed in  56d5af3

Otherwise I just did a bit of code tidying and overall I think now should be good to go. Thanks for all your work on this!

2024-06-19 11:42 UTC, merged